Proxmark/proxmark3

armsrc/lfops.c

fixes bug re-introduced in last commit with the bigbuf changes

lf hid fskdemod bug

---

client/cmddata.c

minor change,  since loop is jumping 16steps at a time, check to make sure it is not overflowing.

bounds check for loop - printDemodBuff

---

client/Makefile

This is based on @iceman1001's proposal but doesn't rely on environment variables (except QTDIR) and/or executables.
This works for me and my (Qt4) environment. Can someone please test if this works for Qt5 as well?

(issue #47) use Qt5 includes and libraries, if present

---

common/lfdemod.c
common/lfdemod.h

missed two files for last push..  sorry

FIX EM Error

---

armsrc/appmain.c
armsrc/lfops.c
armsrc/lfsampling.c
armsrc/lfsampling.h
client/cmddata.c
client/cmddata.h
client/cmdlf.c
client/cmdlfem4x.c
client/cmdlft55xx.c
client/cmdlft55xx.h
client/scripts/test_t55x7_ask.lua
client/scripts/test_t55x7_bi.lua
client/scripts/test_t55x7_fsk.lua
client/scripts/test_t55x7_psk.lua
client/scripts/tracetest.lua
common/lfdemod.c
common/lfdemod.h

A lot of work went into this one, by ICEMAN and myself.  I have done a lot of testing and the t55xx read commands are not perfect but much better.  and I am pretty sure we haven't broken anything... :)
lf t55xx read/write/detect + more commands from ICEMAN :)
lf em410x commands updated/fixed
lf search bug fixed
test scripts from ICEMAN
lfdemod:
better ask clock detection for strong antennas
better rawdemod ar for strong antennas
adjust fsk, nrz, askraw/biphase for working with the ata55xx read functions
add checksums to ioprox (thanks ICEMAN)

lf ata55x7 commands and more

---

armsrc/lfops.c
client/cmddata.c
client/cmdlf.c
common/lfdemod.c

Spacing changes ONLY - no code changes

Fixed indents to Tabs from Spaces

---

armsrc/mifarecmd.c
client/cmdhfmfu.c

Thanks @iceman1001 for catching my oops, and fixing it :)

fix mfu dump getbigbuffer bug

---

client/cmdhfmf.c

After @iceman1001 comment on PR #106, this PR fixes cload & csave.

Fix filenames for hf mf cload / csave

---

COMPILING.txt

Add compiling manual for MAC OS X

Compiling manual for MAC OS X

---

client/cmdhfmf.c

Thanks: @iceman1001 for the suggestion.

Ported hf mf esave trick for unreadable UIDs to hf mf csave

---

armsrc/iso14443.c

masked by a big DMA_BUFFER_SIZE.

Fix issue #103 (hopefully). Quite an old bug which was previously

---

client/cmddata.c

i missed a bug in last pull i made by passing a 0 instead of a pointer to invert.. :(

askbiphase bug fix

---

armsrc/iso14443a.c
armsrc/mifarecmd.c
client/cmdhfmf.c
client/mifarehost.c

hf mf mifare: gracefully exit if tag isn't vulnerable to this attack
hf mf nested: dito

(implementing suggestion #94)

---

armsrc/BigBuf.c
armsrc/des.c
client/cmddata.c
client/cmdhfepa.c
client/cmdhficlass.c
client/cmdlft55xx.c
client/cmdlft55xx.h
client/loclass/cipherutils.c
client/util.c
client/util.h

more t55xx commands support the Q5 or t5555 chip.

q5 fixes plus a couple coverity scan fixes from @iceman1001

---

CHANGELOG.md
armsrc/Makefile
armsrc/appmain.c
armsrc/apps.h
armsrc/hitag2.c
armsrc/hitagS.c
client/cmdlfhitag.c
client/hid-flasher/usb_cmd.h
include/hitag2.h
include/hitagS.h
include/usb_cmd.h

We presented our work on the HitagS at the 32c3. This is the experimental code for the proxmark.
https://events.ccc.de/congress/2015/Fahrplan/events/7166.html
Please review and merge.

Experimental HitagS support

---

COMPILING.txt

Add details to compile using brew in Mac OS X

---

client/fpga_compress.c

Code cleanup

---

client/Makefile

e:/proxspace/mingw/bin/../lib/gcc/mingw32/4.4.0/../../../../mingw32/bin/ld.exe: cannot find -ltermcap
collect2: ld returned 1 exit status
make: *** [proxmark3] Error 1
e:/proxspace/mingw/bin/../lib/gcc/mingw32/4.4.0/../../../../mingw32/bin/ld.exe: cannot find -lncurses
collect2: ld returned 1 exit status
make: *** [proxmark3] Error 1

minor fix in client/makefile

---

client/cmddata.c
client/cmdlfcotag.c
client/graph.c
common/lfdemod.c
common/lfdemod.h

re-organize lfdemod.c
refactor detectST function some
refactor pskdemod some.
prep for additional graphing ability to graph demods
add miller decoding for lf.  needs to be tied into data commands. later...
prep for data.c re-factor to come.
i don't want this pull getting bigger so i thought i'd submit even though there is more to come.

lfdemod refactor

---

CHANGELOG.md
client/cmddata.c
client/cmddata.h
client/cmdlfawid.c
client/cmdlfawid.h
client/cmdlfhid.c
client/cmdlfhid.h

see changelog.md for cli changes as some commands have changed!

split hid demod/awid demod to respective files

---

client/util.c

- don't use CMIN and CTIME
- corrected comments

fix: ukbhit() for OS X

---

CHANGELOG.md
client/cmddata.c
client/cmddata.h
client/cmdlfviking.c
client/cmdlfviking.h

see changelog.md for cli changes!

move viking demod to respective file

---

client/cmdlfawid.c
client/cmdlfawid.h
client/cmdlfem4x.c
client/cmdlfem4x.h
client/cmdlfhid.c
client/cmdlfio.c
client/cmdlfpyramid.c
client/cmdlfviking.c

thanks @iceman1001 for noticing.

fix lf file includes to include own .h

---

.gitignore
client/Makefile
client/cmdhfmf.c
client/mfkey.c
client/mfkey.h
client/mifarehost.c
client/mifarehost.h
common/crapto1/readme
tools/mfkey/Makefile
tools/mfkey/mfkey32.c
tools/mfkey/mfkey64.c

- rename client/nonce2key.[ch] to mfkey.[ch]
- leave only main() wrapper in tools/mfkey
- support Moebius attack in mfkey32
- add mfkey32 and mfkey64 to .gitignore

Deduplicate mfkey32 and mfkey64

---

CHANGELOG.md
client/Makefile
client/cmddata.c
client/cmddata.h
client/cmdlf.c
client/cmdlfindala.c
client/cmdlfindala.h

see changelog.md for cli changes!

split lf indala[cmd] to lf indala [cmd]

---

armsrc/hitag2.c
armsrc/hitagS.c

from
https://github.com/iceman1001/proxmark3/commit/e1778858ddc53a6a82e8ee24f02e6b673687f69a
and http://www.proxmark.org/forum/viewtopic.php?pid=26733#p26733
sim mode should not have the reader field on.

hitag sim fix

---

CHANGELOG.md
client/Makefile
client/cmddata.c
client/cmddata.h
client/cmdlf.c
client/cmdlfgproxii.c
client/cmdlfgproxii.h
client/cmdlfpresco.h
client/cmdlfviking.c
client/cmdlfviking.h
client/cmdlfvisa2000.c
client/cmdlfvisa2000.h

See changelog.md for cli changes!
added lf gproxii read (from antenna)
fixed a few copy/paste issues in the comments of some lf files

Split data askgproxiidemod to own file

---

CHANGELOG.md
client/Makefile
client/cmddata.c
client/cmdlf.c
client/cmdlffdx.c
client/cmdlffdx.h
common/lfdemod.c

added @iceman1001 s read/sim/clone commands for fdx-b
check changelog.md for cli changes!

split fdx-b demod to its own file

---

client/cmdlffdx.c

http://www.proxmark.org/forum/viewtopic.php?pid=26786#p26786

fix missing header

---

client/cmdlfindala.c

fix indentation warning

---

CHANGELOG.md
client/Makefile
client/cmddata.c
client/cmddata.h
client/cmdlf.c
client/cmdlfnexwatch.c
client/cmdlfnexwatch.h
client/cmdlfparadox.c
client/cmdlfparadox.h

see changelog.md for cli changes!

split lf paradox/nexwatch into own files

---

CHANGELOG.md
client/Makefile
client/cmdlf.c
client/cmdlfjablotron.c
client/cmdlfjablotron.h
client/cmdlfnoralsy.c
client/cmdlfnoralsy.h
client/cmdlfsecurakey.c
client/cmdlfsecurakey.h

Thanks to @iceman1001 for most of the code.

Add lf jablotron & lf noralsy tag definitions/cmds

---

client/cmddata.c

I don't even know what happened there...

Fix data mtrim

---

common/usb_cdc.c

- indicate compliance with USB release 2.0
- set correct vendor and product IDs
- indicate power consumption (500mA)
- add String Descriptor 0 indicating supported languages
- add String Descriptors for Manufacturer and Product

fix USB descriptors

---

.gitignore
client/cmdhfmfhard.c
client/hardnested/hardnested_bf_core.c
client/hardnested/hardnested_bitarray_core.c

plus add Td to gitignore.
unless someone has a better solution ;) this fixes #300 for me. (and probably @Gator96100 )

make hardnested compile on gcc 4.9.2

---

client/Makefile
client/cmdhf14a.c
client/cmdhfepa.c
client/cmdhfmf.c
client/cmdhfmfhard.c
client/cmdmain.c
client/flash.c
client/flasher.c
client/hardnested/hardnested_bruteforce.c
client/loclass/elite_crack.c
client/util.c
client/util.h
client/util_posix.c
client/util_posix.h
tools/mfkey/Makefile
tools/mfkey/mfkey32.c
tools/mfkey/mfkey64.c

- _POSIX_C_SOURCE must not be defined for num_CPU()

Fix compile errors with MacOS

---

CHANGELOG.md
armsrc/appmain.c
armsrc/apps.h
armsrc/hitag2.c
client/cmdlfhitag.c
include/hitag2.h

Hi,
I have added a writer function for hitag2 in crypto mode. I have only tested it on a Honda Civic key so far so there might be problems with other tags.
Usage is similar to hitagS write:
lf hitag write 24 KEY pagenumber 32bitvalue
Best regards,
Henrik

hitag2 write

---

CHANGELOG.md
client/cmddata.c
client/cmdlf.c
client/cmdlfindala.c
common/lfdemod.c

allows very weak fsk signal to be demodulated.
usage:
```
lf read
data fsktonrz
data rawdemod nr
```

add data fsktonrz fsk cleaning util

---

CHANGELOG.md
client/cmdlf.c
client/cmdlfpac.c
client/cmdlfpac.h
client/cmdlfsecurakey.c

lf pac read - read from antenna and demod
lf pac demod - demodulate from graphbuffer
fix typo in securakey

add lf PAC/Stanley tag read

---

client/Makefile

Fix missing reference for PAC/Stanley

---

client/cmdlfio.c

fix lf io clone (issue #331):
- remove confusing message about simulation
- add h (help) parameter and usage text

fix lf io clone (issue #331):

---

client/scripts/formatMifare.lua

there was a bug in chip recognition

small fix formatmifare.lua

---

client/Makefile

PR for issue #386 
Thx to @uzlonewolf and @iceman1001

Fix gcc version detection (from iceman1001 fork), fix issue #386

---

armsrc/appmain.c
armsrc/lfops.c
client/cmdhflegic.c
client/cmdlf.c

thanks to @iceman1001 for fix.

fix lf sim fpga download overwrites sim buffer

---

client/cmdhfmf.c

fixed #395

---

client/Makefile
tools/mfkey/Makefile

* they are set by some build environments to find include and lib dirs

Don't ignore environment variables CFLAGS and LDFLAGS

---

CHANGELOG.md
client/cmdhfmf.c

- Added `hf mf nested` mode: autosearch keys for attack (from well known keys)
- Added to `hf mf nested` source key check before attack 
- Added to `hf mf nested` after attack it checks all found keys on non-open sectors 
- small refactoring

hf mf nested add some functionality

---

armsrc/appmain.c
armsrc/epa.c
armsrc/iso14443a.c
armsrc/iso14443a.h
armsrc/mifarecmd.c
client/cmdhf14a.c
client/cmdhfmfu.c
client/lualibs/read14a.lua
client/mifarehost.c
client/scripts/14araw.lua
client/scripts/didump.lua
client/scripts/formatMifare.lua
client/scripts/mfkeys.lua
client/scripts/mifare_autopwn.lua
client/scripts/tnp3clone.lua
client/scripts/tnp3dump.lua
include/mifare.h

Don't do iso14443-4 select for mifare emulations on processor cards (IDPrime, SmartMX, …)

---

CHANGELOG.md
client/cmdhfmf.c

added timeouts for check keys in nested

Check keys nested

---

appveyor.yml

Lets put file to root and then all contributors can config appveyor.com to test releases.
Admin can config CI for main repository, but it not necessary)

added CI appveyor.com

---

armsrc/mifarecmd.c
client/mifarehost.c

fixed #441
needs to deep check

identification fix for magic chinese cards

---

appveyor.yml

small improvement in tests

---

armsrc/mifarecmd.c
client/cmdhf14a.c
client/mifarehost.c

code cleaning

---

appveyor.yml

display return values from commands and compare them with value. as promised in #440

appveyor.yml. display return values

---

armsrc/iso14443a.c
client/cmdhf14a.c

small fixes in ReaderIso14443a() (fixed error UID if the card not present)
and added some messages

small fixes in ReaderIso14443a()

---

armsrc/iso14443a.c

All is OK, but need to change comment)

change comment

---

client/cmdhf14a.c
client/mifarehost.c
client/mifarehost.h
common/crapto1/crapto1.c
common/crapto1/crapto1.h

added detect prng type to `hf 14a info` from @iceman1001 fork. Thanks)

improve `hf 14a info`

---

CHANGELOG.md
armsrc/iso14443a.c
client/Makefile
client/cmdhf14a.c
client/cmdhf14a.h
client/cmdhfmfu.c
client/cmdhfmfu.h
client/emv/apduinfo.c
client/emv/apduinfo.h
client/emv/dump.c
client/emv/dump.h
client/emv/emv_tags.c
client/emv/emv_tags.h
client/emv/emvcore.c
client/emv/emvcore.h
client/emv/tlv.c
client/emv/tlv.h
client/util.c
client/util.h
include/mifare.h

command `hf 14a apdu` works #447

added `hf 14a apdu` #447 part 3

---

client/cmdhf14a.c

revert field on/off in hf 14a reader, fix typo

---

client/emv/dump.c
client/emv/dump.h
client/emv/emv_tags.c
client/emv/emv_tags.h
client/emv/emvcore.c
client/emv/tlv.c
client/emv/tlv.h

before:
```
proxmark3> hf 14a apdu -s -t 00A404000E325041592E5359532E444446303100
>>>>[sel TLV] 00 a4 04 00 0e 32 50 41 59 2e 53 59 53 2e 44 44 46 30 31 00
<<<< 6f 41 84 0e 32 50 41 59 2e 53 59 53 2e 44 44 46 30 31 a5 2f bf 0c 2c 61 23 4f 07 a0 00 00 00 03 10 10 50 0d 56 69 73 61 20 50 6f 73 74 62 61 6e 6b 9f 0a 08 00 01 05 02 00 00 00 00 bf 63
04 df 20 01 80 90 00
APDU response: 90 00 - Command successfully executed (OK).
TLV decoded:
--6f[41] 'File Control Information (FCI) Template':
00: 84 0e 32 50 41 59 2e 53 59 53 2e 44 44 46 30 31 |..2PAY.SYS.DDF01
10: a5 2f bf 0c 2c 61 23 4f 07 a0 00 00 00 03 10 10 |./..,a#O........
20: 50 0d 56 69 73 61 20 50 6f 73 74 62 61 6e 6b 9f |P.Visa Postbank.
30: 0a 08 00 01 05 02 00 00 00 00 bf 63 04 df 20 01 |...........c.. .
40: 80 …
```

add: proper indentation when printing TLV objects

---

client/cmdhfmf.c

fix memory overflow in hf mf nested (issue #479)

fix memory overflow in hf mf nested (issue #479)

---

armsrc/iso14443a.c

Complete WTX handling (pull request #477)

Complete WTX handling (pull request #477)

---

client/scripts/brutesim.lua

A fairly simple script that demonstrates how to bruteforce multiple readers.

Add brutesim script

---

armsrc/iso14443a.c

* take setup frame guard time (SFGT) into account
* adjust iso14a_timeout by FPGA delays
* don't give up on first WUPA. Retry several times

minor iso14443a timing fixes to avoid select errors

---

README.md

This would really make the repo less of an eyesore!

Make README file markdown

---

client/emv/cmdemv.c
client/emv/emv_tags.c
client/emv/emv_tags.h
client/emv/emvcore.c
client/emv/emvcore.h

transactions MSD and M/Chip, qVSDC works
the rest: SDA,DDA,CDA will be added in next PR's

EMV3. hf emv exec 2nd part

---

client/cmdhficlass.c

ADD: 'hf iclass chk'  - new command to check for keys from a dictionary file. 
hf iclass chk h
hf iclass chk f default_iclass_keys.dic

ADD: 'hf iclass chk'

---

client/cmdhficlass.h

ADD 'hf iclass chk'  -  part2

---

client/cmdhficlass.c

added the options 
E -   target elite keys
R -  interpret dictionary keys as raw (already diversified keys)

'hf iclass chk' part3

---

client/loclass/cipher.c
client/loclass/cipher.h
client/loclass/cipherutils.c
client/loclass/cipherutils.h
client/loclass/elite_crack.c
client/loclass/elite_crack.h
client/loclass/fileutils.c
client/loclass/fileutils.h
client/loclass/ikeys.c
client/loclass/ikeys.h
client/loclass/main.c

applying @holiman's changes. See Issue #527.

Update loclass license conditions

---

client/cmdhf14a.c
client/cmdhf14a.h
client/emv/crypto_polarssl.c
client/emv/emv_pki.c
client/emv/test/crypto_test.c
client/util.c

* fix compiler warnings on Ubuntu
* cmdhf14a.c: make manufactureMapping static
* cmdhf14a.c: fix format strings

Minor fixes

---

client/Makefile
client/cmdhfmf.c
client/cmdhfmfhard.c
client/hardnested/hardnested_bf_core.c
client/hardnested/hardnested_bf_core.h
client/hardnested/hardnested_bruteforce.c

#404 
something like that.
its OK?
complete it?

hardnested SIMD select

---

armsrc/appmain.c

CHG:  'hw tune'  adapting LF measuring from ( >> 8) max 65v,  to ( >>9 ) max 130v in the graph data.   Max LF voltage is 140.8v to measure.
Added a delay for antenna coil and caps to power up before measuring,
removed a variable in ReadAdc

HW TUNE adapting for powerful antennas.

---

armsrc/mifarecmd.c
armsrc/mifareutil.h

* .Sacrifice some speed in favor of stability for some card types. Fix issue #518.

Revert some changes in hardnested nonces collection

---

armsrc/appmain.c
client/cmddata.c

* scale results to allow higher LF voltages
* remove historic comments

hw tune improvements (based on issue #544)

---

armsrc/iso14443a.c
armsrc/mifaresniff.c
armsrc/mifaresniff.h
client/mifarehost.c

@iceman1001 check this please)

`hf mf sniff` not a small fix

---

client/cmdhfmfhard.c
client/emv/apduinfo.c
client/fpga_compress.c
client/hardnested/hardnested_bruteforce.c
client/util_posix.c

identified in http://www.proxmark.org/forum/viewtopic.php?id=5388

fix clang compiler warnings

---

client/cmdhfmfhard.c
client/mifarehost.c
client/proxmark3.c

* inspired by issue #404 and respective fix PR #538
* possible fix for mysterious crashes, e.g. issue #497 and http://www.proxmark.org/forum/viewtopic.php?id=5388

add force_align_arg_pointer attribute to all callback functions

---

client/mifarehost.c

fix: prevent hf mf mifare from always running twice

---

armsrc/iso14443a.c
client/mifarehost.c

* prevent WDT crash on repeated tries
* comes with faster execution as side effect
* use uint8_t instead of byte_t
* populate ar instead of (correctly) assuming that it is zero
* remove the "will take a few seconds longer" message because it is no longer true

fix hf mf mifare (WDT crash)

---

armsrc/mifarecmd.h
armsrc/mifaresniff.c
client/cmdhfmf.c
client/mifarehost.c
client/mifarehost.h
client/util.c
client/util.h
common/parity.h

`hf mf sniff` nested works. #557.
hardnested not works and i have no idea how to implement it.
it takes to much time to check and it needs to check command's CRC after authentication.

`hf mf sniff` nested works

---

CHANGELOG.md
armsrc/lfops.c
armsrc/lfsampling.c
client/cmdlf.c
client/cmdmain.c

create bitbang mode if delay is 0
adjust so use full lf config options are used on read-back (and divisor on send)
turn off antenna at completion
auto run `data samples` at completion

improve lf cmdread

---

common/lfdemod.c

Reverts Proxmark/proxmark3#588
See comments on old pr

Revert "Fix offset Indala UID display"

---

client/scripts/lf_bulk_program.lua

Previous pull request was missing some changes.

Fix for swapped parity when using LF bulk Program

---

client/comms.c
client/comms.h
client/proxmark3.c

USB comms: part 3 towards @micolous PR #463
* change variable 'sp' from global to static
* move code to open and close USB port to comms.c (OpenProxmark() and CloseProxmark())
* change scope of USBCommandReceived() to static
* (flasher still unchanged)

USB comms: part 3 towards @micolous PR#463

---

armsrc/appmain.c
armsrc/hitag2.c
armsrc/hitagS.c
armsrc/iclass.c
armsrc/iso14443b.c
armsrc/iso15693.c
armsrc/lfops.c
armsrc/mifarecmd.c
armsrc/mifaresniff.c
armsrc/printf.c
client/cmdhf.c
client/cmdhf14a.c
client/cmdhfepa.c
client/cmdhflist.c
client/cmdhfmf.c
client/cmdhfmfhard.c
client/cmdhfmfu.c
client/cmdhftopaz.c
client/cmdlfhitag.c
client/cmdlfindala.c
client/emv/crypto_polarssl.c
client/flash.c
client/fpga_compress.c
client/mifarehost.c
client/proxgui.cpp
client/proxguiqt.h
client/scripting.c
client/util_posix.c
include/proxmark3.h
tools/mfkey/mfkey32.c

* coverity fixes (including a real bug in cmdhftopaz.c)
* Typo fix
* replace TRUE/FALSE by stdbool true/false

Some code cleanup

---

.gitignore

Prevent further commits containing DS_Store files.

Ignore DS_Store

---

client/cmdlft55xx.c

fix truncation issue on "lf t55 config d" 

---

armsrc/Makefile
armsrc/appmain.c
armsrc/fpgaloader.c
armsrc/fpgaloader.h
bootrom/Makefile
client/cmdhw.c
client/fpga_compress.c
common/Makefile.common
common/fpga.h

* create fpga version info at compile time (by additional functionality in fpgacompress)
* remove hw version caching (prepare USB reconnect)
* fix calculation of available compressed bytes in fpga_loader.c

mod: hw version

---

CHANGELOG.md
armsrc/Makefile
armsrc/appmain.c
armsrc/i2c.c
armsrc/i2c.h
client/Makefile
client/cmdhf.c
client/cmdmain.c
client/cmdsmartcard.c
client/cmdsmartcard.h
common/Makefile_Enabled_Options.common
common/lfdemod.c
common/protocols.h
include/smartcard.h
include/usb_cmd.h

Adds:
`sc raw`
`sc reader`
`sc info`
`sc list`
`sc upgrade`
`sc setclock`
if the smartcard option is included in makefile_enabled_options.common.
by default it is not included!

Add Smartcard functions (RDV4.0)

---

CHANGELOG.md
armsrc/fpgaloader.h

I found an a build error introduced in #669. This PR fixes it. I've additionally used the opportunity to add Legic sim #666 to change log.

Update changelog and fix build error 

---

client/emv/emv_tags.c

added EMV tag #9F6E

---

client/emv/apduinfo.c

https://github.com/RfidResearchGroup/proxmark3/commit/4fa0835d5f7823b9b850be7c7162a98f9a3973a2

FIX: APDUCodeTable has more items than 100

---

client/cliparser/cliparser.c
client/cliparser/cliparser.h
client/cmdhf14a.c
client/emv/cmdemv.c

modify argtable parser to parse ints with spaces

---

armsrc/iso15693.c
client/cmdhf15.c

* implement a real time Decoder (will be required for sniffing)
* switch off field after each command (protect rdv40)
* correctly signal field status with LED D

start fixing hf 15:

---

CHANGELOG.md
client/cmdhfmfp.c
client/mifare4.c
client/mifare4.h
common/polarssl/libpcrypto.c

Have happy, healthy and fun Halloween!

changes to mifare plus code

---

client/emv/tlv.c

fix get length in tlv

---

client/jansson/dump.c
client/jansson/error.c
client/jansson/hashtable.h
client/jansson/hashtable_seed.c
client/jansson/jansson.h
client/jansson/jansson_private.h
client/jansson/load.c
client/jansson/pack_unpack.c
client/jansson/path.c
client/jansson/strbuffer.h
client/jansson/value.c

jansson update. 2.11 to 2.12

---

client/cmdhfmf.c

Trailer decoding support for `rdsc` and `cgetsc` commands.

Mifare trailer block decoding for sector commands

---

client/cliparser/argtable3.c

avoid compiler warning in client/cliparser/argtable3.c

---

client/emv/cmdemv.c

Fix issue: `‘ERROR’ undeclared (first use in this function); did you mean ‘ERR’?`.

Fix PrintAndLogEx ERR

---

client/cmdsmartcard.c

Restore #755: reverted after #757

Restore #755 reverted after #757

---

client/emv/cmdemv.c
client/emv/emv_pk.c
client/emv/emv_pki.c

* fix ICC Public Key Hash calculation
* add -a option to 'emv roca'
* replace print() by PrintAndLogEx() in emv_pki.c

fix emv roca hash error

---

client/cmdhflist.c
client/cmdsmartcard.c
client/emv/emvcore.c
client/pcsc.c
client/pcsc.h
common/protocols.h

* add trace buffer for PCSC smartcard readers
* new option 'p' in 'hf list' to select PCSC trace buffer
* 'sc list' now supports PCSC smartcard readers
* add 'hf list 7816' for ISO 7816-4 protocol (APDUs) 
* add 'hf list 14-4' for ISO 14443-4 protocol

add tracing functions

---

client/cmdsmartcard.c
client/cmdsmartcard.h
client/emv/cmdemv.c
client/emv/tlv.c
client/emv/tlv.h

Emv scan via contact interface

---

include/smartcard.h

* TS, T0, T[A-D][1-4], max. 15 HB, TCK = 34 Bytes

fix ATR length

---

client/Makefile
client/cmdhf14a.c
client/cmdhf14a.h
client/cmdhf14b.c
client/cmdhf15.c
client/cmdhfmfu.c
client/cmdhftopaz.c
client/cmdlft55xx.c
client/taginfo.c
client/taginfo.h

* add more manufacturers
* refactor chipID decoding
* move to separate file taginfo.[ch]

chip manufacturer and type identification:

---

armsrc/appmain.c
armsrc/iclass.c
armsrc/util.c
armsrc/util.h

Just added a couple of LED utility functions. Namely all off and inverted.
I'm a backend developer so most of my debugging is done through the LEDs. Wanted to get feedback on whether this is a welcome change or not.

Added some LED utility functions

---

armsrc/iso14443a.c
armsrc/iso14443b.c

* LED handling
* improve 'hf plot' support

iso14443b modifications

---

client/cmdhfmf.c

Add: new option 'd' in 'hf mf ekeyprn' to create dumpkeys.bin from emulator memory

---

client/cmdhf14a.h
client/cmdhficlass.c
client/cmdhfmf.c
client/cmdhfmf.h
client/cmdhfmfu.c
client/cmdhfmfu.h
client/util.c
client/util.h

* use PrintAndLogEx()
* fix some printouts
* some #include refactoring
* whitespace

start updating 'hf mfu' commands

---

armsrc/pcf7931.c
client/cmdlfpcf7931.c

fix 'lf pcf7931 bruteforce' (bug reported in http://www.proxmark.org/forum/viewtopic.php?id=6490)

---

CHANGELOG.md
armsrc/appmain.c
armsrc/apps.h
armsrc/lfops.c
armsrc/lfsampling.c
client/cmdlf.c
client/cmdlfem4x.c
include/usb_cmd.h

add lf em 4x05protect to allow editing of protection bits on em4x05 chip
add lf config s xxx option to allow skipping x samples before capture.  (use for long snoop captures)

add lf em 4x05protect plus lf config s option

---

armsrc/lfops.c

good catch @mwalker33
see #838

update em4x05 timing

---

client/emv/emvcore.c

* (taken from PRs 261 and 262 by @merlokk on https://github.com/RfidResearchGroup/proxmark3)
* whitespace fixes

fix emv search behavior

---

CHANGELOG.md
client/cmdhf14a.c
client/emv/apduinfo.c
client/emv/apduinfo.h
client/util.h

(PR 249 by @merlokk on https://github.com/RfidResearchGroup/proxmark3)
* print APDU (if it can be decoded)
* construct extended and normal size APDU

'hf 14a apdu' improvement

---

CHANGELOG.md
armsrc/appmain.c
armsrc/apps.h
armsrc/mifarecmd.c
armsrc/mifarecmd.h
armsrc/mifareutil.c
client/cmdhfmf.c
client/util.c
common/protocols.h
include/usb_cmd.h

plus:
* add/use some #defines
* whitespace fixes
* #include refactoring

add: 'hf mf personalize' (personalize UID on Mifare Classic EV1 7byte UID cards)

---

armsrc/apps.h
armsrc/hitag2.c
armsrc/hitag2.h
armsrc/hitagS.c
armsrc/util.h
client/cmdlfhitag.c
client/cmdlfhitag.h
common/protocols.h
include/hitag.h

* (PRs 233, 303, 304 by @ViRb3 on https://github.com/RfidResearchGroup/proxmark3)
* replace byte_t by uint8_t
* note that Hitag1 commands are not yet available
* whitespace fixes

'lf hitag writer': add Hitag2 password auth

---

armsrc/appmain.c
armsrc/apps.h
armsrc/iclass.c
armsrc/iclass.h
armsrc/optimized_cipher.c
armsrc/optimized_cipher.h

See http://www.proxmark.org/forum/viewtopic.php?pid=36292#p36292. The MAC calculation in optimized_cipher.c was too slow (403 microseconds). This PR speeds up the calculation to 270 microseconds.

iClass MAC calculation speedup (optimized_cipher.c)

---

client/loclass/elite_crack.c

* fix handling of "BEING_CRACKED" flag
* don't try to calculate KCus when some bytes couldn't be brute forced
* whitespace fixes

'hf iclass loclass': fix error handling

---

client/cmdhf14b.c

fix 'hf 14b sriwrite'

---

client/cmdhflist.c

* switch to argtable command line parsing (i.e. options must now be preceded by '-')
* add option '-r' to display relative times
* add option '-u' to display times in microseconds
* fix: graceful exit if trace is requested from offline PM3

mod 'hf list'

---

armsrc/iclass.c
client/cmdhficlass.c
client/util.c

* Check for Credidt Keys as well
* reduce authentication tries from 6 to 3
* correct text in 'hf iclass clone' for 'l' parameter
* some reformatting and whitespace fixes

fix 'hf iclass chk'

---

armsrc/iso15693.c
armsrc/iso15693.h
client/cmdhf15.c
client/cmdhf15.h
client/cmdhflist.c
common/protocols.h

* check for error codes, prevent client crash
* some include file refactoring
* some whitespace fixes

fix 'hf 15 csetuid'

---

armsrc/mifarecmd.c
client/cmdhf14b.c
client/cmdhfmf.c
client/mifare/mifarehost.c

Fix for #899 .  Ended up also fixing a string-too-small issue in CmdSriWrite().

Nested loop fix

---

client/cmdhf14b.c

* fix memory access violation in HF14B_Other_Reader() (issue #906)

fix hf search

---

CHANGELOG.md
armsrc/mifarecmd.c
armsrc/mifareutil.c
armsrc/mifareutil.h
client/cmdhfmf.c
client/mifare/mifarehost.c
include/mifare.h

* uses a fixed nr_enc and does all the crypto operations on client
* for all possible keys calculate par_enc and ar_enc and send them to device

add a specific check function for static nonces (used in 'hf mf nested')
