Proxmark/proxmark3

armsrc/lfops.c

Fixed standalone bug by re-making the function return the hi and lo
values. (used only by samyrun function in appmain.c)

fix hid prox standalone bug

---

client/cmdlfti.c

FIX:  LF TI WRITE inparameters didn't get copied by sscanf.  This removes the "PRIu64" and uses the 012"llx" instead.

FIX:  LF TI WRITE inparameters didn't get copied by sscanf.

---

armsrc/appmain.c
armsrc/apps.h

... and I modified hw detectreader to display reader field strength in mV units and to be less phony.
See the comments in appmain.c ReadAdc() for some explanation and background.
I came across this bug when looking after the issue #11. Voltage measurements are very wrong. E.g. in hw tune and hf tune we used to see values between 7V (bad) and 14V (very good). Now they would show approx 50% higher.
With regards to issue #11 this will relax the discussion about a correct MF_MINFIELDV.
For discussion: Historic reports of hw tune results will be void from this commit on going forward. Would we want to accept this confusion?

Bugfix hw tune, hf tune: voltage measures were VERY wrong

---

client/cmdhfmf.c
client/mifarehost.c
client/mifarehost.h

There seemed to be someone's code forcing all csetuid calls to set ATQA: 0f01 SAK: 01 (NXP TNP3xxx Activision Game Appliance) instead of preserving existing ATQA/SAK. As there seemed to be need to set ATQA and SAK, I added them as an optional argument.

Add settable ATQA and SAK to hf mf csetuid command.

---

client/cmddata.c
client/cmddata.h

new:
data rawdemod
replaces:
data askmandemod
data askrawdemod
data fskrawdemod
data nrzrawdemod
data psk1rawdemod
data psk2rawdemod
also commented out of the CommandTable but did not remove the commands:
data askdemod
data bitstream
data fskdemod
data mandemod
data threshold
anyone know a reason to keep these in data please speak up.

lf data combine rawdemods & depreciate cmds 

---

armsrc/lfops.c

This means the LF sim will be aborted whenever something comes over the USB. This is probably a good thing, but I haven't tested it very thorougly, so I don't know if the check could possibly cause us to miss a beat in the simulation. The `usb_poll`-check looks like it is very quick, checking ARM-registers, but in the borderline between hardware and software, I'm never too sure...

Implemented usb_poll() within LF sim. 

---

Makefile
armsrc/Makefile
armsrc/ldscript
common/ldscript.common
common/lfdemod.c

- added compiler options -fdata-sections and -ffunction-sections (thanks to iceman for the hint)
- removed float operations from common/lfdemod.c to avoid adding float libraries to the ARM os image
- moved the fpga images to the data section to avoid reserving unused space for a separate section

Reclaim more than 19K of ARM flash memory.

---

armsrc/iso14443a.c
client/cmdhf14a.c
client/scripting.c

mf sim 7 byte uid bug
identifying MF UL, UL-C, UL-EV1 differences
scripting aes bug.

Iceman's fixes for #93, #96, #97

---

client/cmdhfmf.c

Since https://github.com/Proxmark/proxmark3/commit/e6432f05795ba0eaf1e34bb47b2a7f87a762de29, `hf mf esave` and `hf mf eload` have been broken. I think this PR fixes both of them, plus addresses an issue when `hf mf esave` was used without a providing a filename and the client was not able to get the UID (`else` missing).

Fix filenames for hf mf esave / eload

---

armsrc/appmain.c
armsrc/apps.h
armsrc/epa.c
armsrc/epa.h
client/cmdhfepa.c
include/usb_cmd.h

This function allows the user to specify APDUs which are sent to a card
supporting the PACE protocol. The response times are measured and
printed.
The code was pulled from the old Google Code repository (branch "epa")
and modified to fit into the new code base.

Add PACE replay functionality

---

client/fpga_compress.c

The comparison would check for greater-than-or-equal the maximum amount
of bytes to read/write when it should check for greater-than only.
The error was introduced in pull request #109.

Fix comparison error in fpga_compress

---

CHANGELOG.md
armsrc/Makefile
armsrc/epa.c
armsrc/epa.h
armsrc/iso14443b.c
armsrc/iso14443b.h

This adds 2 new functions to iso14443b.c: iso14443b_setup and iso14443b_apdu which perform tasks similar to their counterparts in iso14443a.c. On the long run this should facilitate building functionality that is type-independent (i.e. supports both A and B tags).
As a first implementation, the functionality related to the German ID card (epa.c) has been updated to support both types.
Experiments so far show that both types work fine and can be used for the same tasks.

ISO 14443 type B support for (German) electronic ID cards

---

CHANGELOG.md
armsrc/appmain.c
armsrc/apps.h
armsrc/lfops.c
client/Makefile
client/cmdlf.c
client/cmdlfawid.c
client/cmdlfawid.h
client/hid-flasher/usb_cmd.h
client/lualibs/commands.lua
include/usb_cmd.h

These changes build upon Marshmellow's AWID demodulation function by adding the 'lf awid' conext for working with AWID26 format tags.  The main advantage of this command context is that it allows one to simulate or clone an AWID26 tag based on the facility code and card number typically printed on the card without needing to manually calculate the tag's raw bitstream.

AWID26 Extended Support

---

armsrc/appmain.c
armsrc/lfops.c
client/cmdhw.c
client/cmdlfawid.c
client/cmdlft55xx.c
common/usb_cdc.c
common/usb_cdc.h

These are fixes to Craig Youngs AWID-code. Three things:
- Indentation (meh)
- The issue where a 0-byte usb-packet appears in the ARM, and disturbs the `usb_poll` check. Added a better usb_poll which checks that the length is > 0. 
- The issue that packets (writes) are lost. Added `ack` packets to t55-writes, and waiting on those acks from the client. 
I haven't actually tested any of this, embarrassingly enough, a bit short on time, OSX, and correct tags, that's why I've put it as a PR instead, so it'd be great if someone with tags (and OSX) can check it out.

Fixes to PR #129

---

CHANGELOG.md
armsrc/Makefile
armsrc/appmain.c
armsrc/apps.h
armsrc/lfops.c
client/Makefile
client/cmdlf.c
client/cmdlfawid.c
client/cmdlfawid.h
client/hid-flasher/usb_cmd.h
client/lualibs/commands.lua
include/usb_cmd.h

In addition to AWID26 support, I have also prepared changes to enable NFC uid reading and emulation from stand-alone mode.  UID cloning is also implemented when using a compatible Mifare card.
Sorry for getting this code change mixed up into the same pull request as the AWID26 changes, but I am not familiar enough with GitHub to do it another way short of another fork & pull approach.

ISO14443a Stand-Alone Mode

---

CHANGELOG.md
armsrc/iso14443b.c
armsrc/lfsampling.c
client/cmddata.c
client/cmdhf14b.c
client/cmdlf.c
common/lfdemod.c

change lf config threshold to trigger on top or bottom of wave and is based on graphing metric 0-128.  
add SRx tag lock bit info to hf 14b info command
add SRx tag select to hf 14b raw (-ss option)
add more 14b sim command responses
fixed fdx-b false positives by verifying marker bits and length

14b additions + some bug fixes

---

client/cmdhf14a.c

The value `x0` was obviously copypasted but not edited to reflect the real values used in `case` matching.

Fixed copypasted hex output to match input

---

Makefile

Without this commit, running `make help` produced the below output.
$ make help
Multi-OS Makefile, you are running on Linux
Possible targets:
+ all - Make bootrom, armsrc and the OS-specific host directory
+ client - Make only the OS-specific host directory
+ flash-bootrom - Make bootrom and flash it
/bin/sh: 1: Syntax error: "(" unexpected
Makefile:20: recipe for target 'help' failed
make: *** [help] Error 2
This issue was introduced in e335ca2846d57f660ab7f4c75b58226cca264e0e six months ago, the above output was produced on Debian GNU/Linux, where `/bin/sh` is usually a symbolic link to `/bin/dash`.

fixed target "help" in Makefile

---

.gitignore
CHANGELOG.md
armsrc/appmain.c
armsrc/fpgaloader.c
armsrc/fpgaloader.h
client/cmddata.c
client/cmdhw.c
include/usb_cmd.h

Save time and fpga downloads by only tuning lf/hf as required. If both are required the order is optimized to avoid unnecessary download (i.e. always used to do lf first, but if hf core already loaded will now do the hf first).

add l/h option to hw tune and optimize order of tuning

---

liblua/Makefile

This action fixes the compilation issue on Slackware Linux 14.2.
```
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libreadline.so: undefined reference to `BC'
collect2: fel: ld returnerade avslutningsstatus 1
Makefile:63: receptet för målet "lua" misslyckades
make[3]: *** [lua] Fel 1
make[3]: Lämnar katalogen "/home/github/proxmark3/proxmark3/liblua"
Makefile:106: receptet för målet "linux" misslyckades
make[2]: *** [linux] Fel 2
make[2]: Lämnar katalogen "/home/github/proxmark3/proxmark3/liblua"
Makefile:163: receptet för målet "lua_build" misslyckades
make[1]: *** [lua_build] Fel 2
make[1]: Lämnar katalogen "/home/github/proxmark3/proxmark3/client"
Makefile:12: receptet för målet "client/all" misslyckades
make: *** [client/all] Fel 2
make: Lämnar katalogen …
```

Patching Lua compilation error

---

client/Makefile

Addition of termcap and ncurses libraries fixes the compilation issue on Slackware Linux 14.2.
```
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libreadline.so: undefined reference to `PC'
collect2: fel: ld returnerade avslutningsstatus 1
Makefile:132: receptet för målet "proxmark3" misslyckades
make[1]: *** [proxmark3] Fel 1
make[1]: Lämnar katalogen "/home/github/proxmark3/proxmark3/client"
Makefile:12: receptet för målet "client/all" misslyckades
make: *** [client/all] Fel 2
make: Lämnar katalogen "/home/github/proxmark3/proxmark3"
```

Better Linux compilation compability

---

client/fpga_compress.c

Minor corrections of data types.
```
gcc -std=c99 -I. -I../include -I../common -I../zlib -I/opt/local/include -I../liblua -Wall  -g -O4 -DHAVE_GUI -DZ_SOLO -DZ_PREFIX -DNO_GZIP -DZLIB_PM3_TUNED  -c -o obj/fpga_compress.o fpga_compress.c
fpga_compress.c: I funktion "zlib_compress":
fpga_compress.c:90:20: varning: format "%lu" förväntar sig argument av typen "long unsigned int", men argument 3 har typen "int" [-Wformat=]
fprintf(stderr, "Input files too big (total > %lu bytes). These are probably not PM3 FPGA config files.\n", num_infiles*FPGA_CONF
^
fpga_compress.c:142:18: varning: format "%lu" förväntar sig argument av typen "long unsigned int", men argument 3 har typen "uint32_t {även unsigned int}" [-Wformat=]
fprintf(stderr, "compressed %lu input bytes to %lu output bytes\n", i, …
```

Warning removal fix

---

client/cmddata.c
common/lfdemod.c
common/lfdemod.h

rawdemod parameter length test too short for help text
amp option should amp prior to ST check
ST check adjusted to make room for rf/32 clock instead of rf/64 (so will
have extra room if clock is higher than 32)
ST check improved to better account for low drift

bug fixes - LF rawdemod am and ST

---

armsrc/iso14443a.c
armsrc/util.c
armsrc/util.h
client/cmdhfmf.c
include/usb_cmd.h

This makes the PM3 generate pseudo-random nonces rather than sequential nonces, to make it act a bit more like a "real" MFC card.  A reader may otherwise be able to detect the PM3 probing based on the predictable nonces and throw different authentication challenges (or refuse to authenticate at all).
The code includes an implementation of a rand-like function (prand), similar to the one from libc, which is seeded automatically based on the time it takes between the PM3 starting up and the first call to the RNG.
This isn't cryptographically random, but should be "good enough" to be able to evade basic detection.
This is [a port of a similar patch I wrote for @iceman1001's branch](https://github.com/micolous/proxmark3/commit/3508ed9eb5257ede1e32039e37e9af0b0060ed83), except this uses a …

Adds random nonce (r) option to `hf mf sim`.

---

CHANGELOG.md
armsrc/appmain.c
armsrc/apps.h
armsrc/lfops.c
armsrc/lfsampling.c
armsrc/lfsampling.h
armsrc/util.c
armsrc/util.h
client/Makefile
client/cmdlf.c
client/cmdlfcotag.c
client/cmdlfcotag.h
client/graph.c
client/graph.h
client/hid-flasher/usb_cmd.h
client/lualibs/commands.lua
include/usb_cmd.h

D__USE_MINGW_ANSI_STDIO=1 needed for some compilers on W32
added iceman1001 s lf cotag read (plus some timer functions)
added check for wave in graphbuffer and test in lf search, don't try hitag or cotag tests if wave exists.

Add Flag for compile warnings, lf cotag read by iceman

---

client/lualibs/hf_reader.lua

Fix variable name typo in hf_reader library

Fix recvLen variable name in hf_reader

---

CHANGELOG.md
armsrc/lfops.c
client/cmddata.c
client/cmdhfmf.c
client/proxgui.h
client/proxguiqt.cpp
client/ui.c
client/ui.h
common/lfdemod.c
common/lfdemod.h

Add a retry loop in `hf mf dump` to retry each read up to 3 times (helps fix #200 )
Fixed a small bug in STT detection for strong (or cleaned) signal.
Fixed a bug preventing the detection of EM410x XL format AKA Unique XL or 128 bit Unique ID
add `data setgraphmarkers` <orange> <blue> to allow setting markers on the graph
add `data mtrim` <start> <stop> to allow middle trimming (or trimming out samples between start and stop)
make the askmandemod mark the first STT on the graph if it is found

small patches and small added features listed below:

---

client/cmdhfmfu.c
client/util.c
client/util.h

Replace unprintable characters with a dot in the `hf mfu dump` preview to prevent them from scrambling the console output. `cmdhf15.c` does something similar.

Clean mfu dump output

---

client/cmdhw.c

Quick PR to fix a typo in the hw ping command.
Ping successfull -> Ping successful

Typo fix for CmdPing

---

client/Makefile
client/hid-flasher/proxendian.h
client/hid-flasher/sleep.h

- Use -D_ISOC99_SOURCE instead of -D__USE_MINGW_ANSI_STDIO=1
- WIN32 is deprecated. Use _WIN32 instead

Fix some #defines

---

client/cmddata.c
client/cmdhf.c
client/cmdhf14a.c
client/cmdhfmf.c
client/cmdhfmf.h
client/cmdhfmfu.c
client/cmdlf.c
client/cmdlfcotag.c
client/cmdlfcotag.h
client/cmdlft55xx.c
client/cmdmain.h
client/mifarehost.c
client/mifarehost.h
client/nonce2key/nonce2key.c
client/util.h
client/whereami.c

- cleanup some header files and respective #includes
- rearrange functions (definition before first use)
- use SCNxxx instead of PRIxxx macros in scanf()
- use stdbool true/false instead of self defined TRUE/FALSE

Client code cleanup:

---

client/Makefile
client/nonce2key/nonce2key.c
common/crapto1/crapto1.c
common/crapto1/crapto1.h
common/crapto1/crypto1.c
tools/mfkey/Makefile
tools/mfkey/mfkey32.c
tools/mfkey/mfkey64.c
tools/nonce2key/Makefile
tools/nonce2key/nonce2key.c

- fix standalone tools mfkey32, mfkey64 and nonce2key to use common crapto1 library
- fix compiler warnings in tools/mfkey/mfkey64.c and tools/nonce2key/nonce2key.c
- allow crapto1.c to compile on ARM hosts
- add @iceman1001's readme.txt to tools/mfkey

Upgrade crapto1 library to v3.3

---

tools/mfkey/Makefile
tools/mfkey/mfkey64.c

- add -std=c99 -D_ISOC99_SOURCE to compiler flags
- fix: include <string.h> instead of <strings.h> in mfkey64.c

fix mfkey tools (issue #247)

---

client/util.c

Some versions of MinGW miss some definitions. In order to be able to
compile I redefined a function and added an explicit include. It is only
a quick workaround, as other people also seemed to have the same
problem. It should be checked whether a better solution is possible.

Fixed compile error in MinGW

---

CHANGELOG.md
armsrc/lfops.c
client/cmddata.c
client/cmddata.h
client/cmdlf.c
client/cmdlfnoralsy.c
client/cmdlft55xx.c
client/cmdlft55xx.h
client/graph.c
client/util.c
common/lfdemod.c
common/lfdemod.h
common/protocols.h

fixes #267 
also fixes a bug in noralsy demod.
improves lf sequence terminator(ST) detection
improves lf t55xx detection and reading.
fixes a bug in sprint_bin_break (didn't print last bit)
fixes a bug in lf indala demod corrupting the end of the ID sometimes
improves psk and nrz detection / demodulation
added t55xx page 1 detection and added it to the lf search chip detection. (based on mfg code E015)
added experimental t55xx testmode write command. (careful.  can and will overwrite entire tag no matter the selected block)

various lf bug fixes and improvements

---

client/Makefile
client/proxguiqt.cpp

- make Qt detection in client/Makefile independent of OS
- added -std=c++11 and -fPIC as compiler options (required by some Qt versions, breaks compiling with old ProxSpace environment)

Compatibility fixes for Qt5

---

client/scripts/lf_bulk_program.lua

Submitting a well documented Lua script whose purpose is to do
bulk, repeated, sequential programming of RFID tags.  Could be useful
for users of the ACCX Open Access 4.0 or other simple RFID systems.
Tags programmed with this would potentially be vulnerabile to bisection
attacks, etc... But honestly, they likely would have been anyway.
To use run from within the proxmark3 client:
```
proxmark3> script run lf_bulk_program.lua  -b 1000 -c 5 -f 23
--- Executing: lf_bulk_program.lua, args '-b 1000 -c 5 -f 23'
Press enter to program card 1000:23 (hex: 0020042e07d1)
Cloning tag with ID 20042e07d1
Press enter to program card 1001:23 (hex: 0020042e07d2)
Cloning tag with ID 20042e07d2
Press enter to program card 1002:23 (hex: 0020042e07d4)
Cloning tag with ID 20042e07d4
Press enter to program …
```

contrib: LF Programming script

---

client/Makefile

(use -std=c++11 and -fPIC options for Qt5 only)
Note: the latest graphwork changes in addition require ProxSpace/qt/4.6.2/bin/uic.exe which is not included in the old proxspace environment. If someone could add it please...

reenable build in old proxspace environment

---

client/proxguiqt.h

Fixes compile errors due to missing typedefs.

Add needed header files to proxguiqt

---

client/Makefile
client/proxgui.cpp
client/proxgui.h
client/proxguiqt.cpp
client/proxguiqt.h
client/proxmark3.c
client/proxmark3.h

Using a `QThread` instead of a `pthread` to run the `main_loop()`. I am still not confident if the cleanup (deleting objects) is OK. However, this happens just before exiting `main()` anyway. Should fix #284.

fixing the crash on exit (issue #284)

---

client/Makefile
client/hardnested/hardnested_bf_core.c
client/hardnested/hardnested_bitarray_core.c

fix compile errors on non-Intel CPUs (issue #303):
- client/Makefile: don't compile for different SIMD instruction sets if non-Intel
- hardnested cores: provide non-SIMD versions of core functions

fix compile errors on non-Intel CPUs (issue #303)

---

client/Makefile

it isn't pretty, but it gets gcc 4.8.2 on ubuntu 14.04 to work (fixes #305)
tested on:
mingw 4.9.2
Kali 2016

fix compile error gcc lt 4.9

---

armsrc/iso14443a.c
client/cmdhf14a.c
client/cmdhfmf.c
client/cmdhfmfu.c
client/cmdlfpresco.c
client/proxguiqt.h

1. mf reader attack could overload the usb packet buffer if 8 keys were found. (dropped to 7)
2. mfu authentication could take a keynumber larger than possible in buffer - fixed
3. 14a raw cmd could overloads uint16_t numbits  line 715 to signed int then to uint64_t  could cause issues. 
4. cmdhfmf line 973 exits without freeing key calloc.
5. couple bugs fixed in cmdlfpresco.c

a few coverity scan bug fixes

---

client/cmdhfmfhard.c
client/hardnested/hardnested_bf_core.c
client/hardnested/hardnested_bitarray_core.c
client/util_posix.c

OSX 10.11 does not have clock_gettime()
clang <= 8.0.0 has a bug in __builtin_cpu_supports() and it doesn't
function.
see https://llvm.org/bugs/show_bug.cgi?id=25510

fix compile issues on OS X 10.11

---

client/scripts/mfkeys.lua

CMD_MIFARE_CHKKEYS command has a different arg1, arg2 meaning nowdays.
Arg0  =  keytype << 8 | blockno 
arg1  = clear trace
In lua its name arg1, probably with lua's startindex is 1...

bug;  Check keys params

---

client/cmdhfmf.c

bug:  'hf mf chk' - size of keycounter variable is too small for dictionary files larger than 256rows.

bug:  hf mf chk - wrong size

---

client/mifarehost.c

BUG: 'hf mf mifare' ,  wrongly identify success when faulty key is found
https://github.com/Proxmark/proxmark3/issues/320

BUG: 'hf mf mifare'

---

client/cmdhficlass.c
common/protocols.c

clean up output
allow readblock without authenticating (can read blocks 0, 1, 2, 5
without authenticating.)
add Application Issuer Area to reader output and use it to attempt to
identify legacy vs NOT legacy.

iclass - updates

---

armsrc/iclass.c
client/cmdhficlass.c

memory locations in code are now accurate and the CC output is not
corrupted by the config's crc.
also the looping and flags for what to read are now correctly
implemented in the code. (still have a redundant loop in the arm code, but there may be a use for it in the future.)

bug fix for hf iclass reader and iclass detection

---

COMPILING.txt
client/ui.c

This fixes up an issue with building the proxmark3 client on OSX, and allows it to build pretty much out of the box (only Xcode and arm toolchain needed) if you don't need GUI support, without installing GNU readline and doing the whole [pivoting dance](https://github.com/Proxmark/proxmark3/issues/110#issuecomment-171015752).
OSX comes with [libedit](http://thrysoee.dk/editline/) instead, which is mostly compatible and shadows GNU readline's header files.  Once built, the imports of `proxmark3` without the GUI look like (on a OSX 10.12 system):
```
$ objdump -dylibs-used -macho proxmark3
proxmark3:
/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
/usr/lib/libc++.1.dylib …
```

OSX: Disable GNU readline-specific hack when libedit is used (fixes #110)

---

armsrc/iclass.c
client/cmdhf.c
client/cmdhficlass.c

endless loop in reader if no tag was found
button press on pm3 did not cancel.
led_b was left on in some cases
also moved 14b detection to last in hf search to help speed up the
command for the other tags.  14b is slow (does multiple tests)
Thanks to @Fl0-0 and @pwpiwi for their idenfication of some of the
issues.
fixes #348

fix some iclass reader bugs

---

client/cmdlfem4x.c

Should fix the warning on mingw on #343

Fix CmdEM410xBrute string format warning

---

armsrc/iso14443a.c
client/mfkey.c
client/mfkey.h
include/mifare.h

After pwpiwi's suggestion I develope a better patch for resolve the issue #377
Fixes 2 bugs in mifare simulate
- Check button press when there is NOFIELD, so we can exit also without FIELD
- struct nonces_t is moved to include/mifare.h so client and arm has the same definition

Fixes 2 bugs in mifare simulate

---

client/proxmark3.c

When running without X (i.e. in a console or remotely via SSH) proxmark crashes with
$ ./proxmark3 /dev/ttyACM0
proxmark3> QXcbConnection: Could not connect to display 
Aborted (core dumped)
$ 
This commit causes proxmark to look at the $DISPLAY environmental variable and run in text-only mode if it's empty or unset.

Don't try to display the GUI when running in textmode

---

client/util_posix.c

This also fixes hf mf hardnested. The buggy clock_gettime() resulted in wrong benchmark results and prevented output of progress and result.

Fix clock_gettime() for Apple OSX

---

armsrc/iso14443b.h

small fix #416 
I dont see why we need to move function definitions to iso14443b.h. When it needs-feel free to do that))))

small fix #416

---

common/usb_cdc.c

The set define under the case "STD_SET_CONFIGURATION" is not the same as here.
The endpoint is configured as INTERUPT not ISOCHRONOUS

[USB,  CDC] wrong define used

---

common/usb_cdc.c

* add some comments and #defines in usb_cdc.c
* use full FIFO size of 64 Bytes for device -> host transfers (thanks to @iceman1001 for noticing this flaw)

Improve device side USB implementation.

---

CHANGELOG.md
client/proxgui.cpp
client/proxgui.h
client/proxguiqt.cpp
client/proxguiqt.h
client/proxmark3.c
client/proxmark3.h
client/util.c
client/util.h

small refactoring + added feature to wait com port on proxmark start

proxmark3 refactoring command line parameters

---

client/pm3_binlib.c

On MacOS might have issues with compilation. This should fix it in a case where liblua used is not the built in one. Issue #428 .

Fixing liblua issues

---

common/usb_cdc.c

- Fix reporting of string descriptors.
- Report device subclass as CDC ACM, to allow driverless operation on Win10+.  Reference:
https://msdn.microsoft.com/en-us/library/windows/hardware/dn707976%28v=vs.85%29.aspx
- Report interface protocol as "None", so we still get picked up as a USB-CDC device while also not being mistaken for a modem (according to the USB spec, but sadly not according to ModemManager).
- Add note [about ModemManager and the manufacturer string](https://lists.freedesktop.org/archives/modemmanager-devel/2016-February/002705.html), so that can be locked in.
There's also some history on #287 on this which is relevant.  I tried using this on Ubuntu, OSX and Windows, though with Windows I only tested that it registered with a COM port.

Cleanup USB string descriptor handling, add note about ModemManager on manufacturer string

---

client/cmdmain.c
client/proxmark3.c
uart/uart_win32.c

* don't ignore ReadLine() errors (Windows)
* lock CmdBuffer with Mutex
* refactor WaitForResponseTimeoutW

fix hw status (and USB comm in general)

---

client/proxmark3.c

Simple patch to see the waiting message properly when using the new option "-w"

Flush stdout when waiting for /dev/ttyACM0

---

client/Makefile
client/cmdlf.c
client/cmdmain.c
client/cmdmain.h
client/cmdparser.c
client/comms.c
client/comms.h
client/flash.c
client/flash.h
client/flasher.c
client/proxgui.cpp
client/proxgui.h
client/proxguiqt.h
client/proxmark3.c
client/proxmark3.h
client/ui.c
client/ui.h
common/iso15693tools.c
include/usb_cmd.h

This is a refactor of exclusively the comms related code from #346, and a part of work for Issue #334:
- Move all globals into a single file (`comms_globals.h`)
- Fix an issue with `proxmark3` built with Qt support quitting on startup
- `flasher` uses same code as `proxmark3` client for communication with hardware
- Fixes a couple of other compilation issues on OSX
This appears to work with me on Linux and OSX with Qt and non-Qt targets.

Comms refactor (prerequisite of libproxmark work)

---

client/cmdhf14a.c

added command `hf 14a info`, 
copy functionality from `hf 14a reader` to `hf 14a info`, 
added command `hf 14a reader` with simple anticollision-select procedure
part of #447

#447 part 1

---

client/cmdcrc.c
client/cmdhf.c
client/cmdhficlass.c
client/cmdhfmf.c
client/cmdhfmfu.c
client/cmdlf.c
client/cmdlfem4x.c
client/cmdlfpresco.c
client/cmdlft55xx.c
client/util.c
client/util.h

There was insufficient memory allocated to a getstr for a UID. In addition, added some checking for that command.

Fix memory bounds error

---

client/cmdhf14a.c
client/util.c

fix timeout set in #481 and fix printf in util.c warning here
```
// Prevent out of bounds errors
if (en - bg + 1 >= buffersize) {
printf("out of bounds error: want %d bytes have %d bytes\n", en - bg + 1 + 1, buffersize);
^^^^            ^^^^^
return 0;
}
```

fix timeout set in #481 and fix printf in util.c warning

---

armsrc/util.c

fix: avoid SspClk overflow due to incomplete reset
* should fix watchdog reset during hf mf mifare (issue #423). Thanks @iceman for the hint.

fix: avoid SspClk overflow due to incomplete reset

---

common/usb_cdc.c

* correctly indicate the maximum current drawn from the USB bus (150mA instead of 500mA)
* should fix the error "[14651.188644] usb 3-13.2: device descriptor read/64, error -110" observed in issue #283

fix: USB Power requirements

---

CHANGELOG.md
client/emv/cmdemv.c
client/emv/emv_tags.c
client/emv/emvcore.c
client/emv/emvcore.h
client/util.c
client/util.h

Added functionality:
- `hf emv exec` - command for execute EMV transaction
- `hf emv exec` MSD path for VISA and Mastercard and some other compatible EMV cards
next part will need more efficient way of working with parameters because there will be huge hill of parameters in `hf emv exec` command)  so, lets talk about in #490
maybe wo parameters i can do something in Mastercard transactions and thats all)

Emv2. next part of EMV work

---

armsrc/iso14443a.c
armsrc/mifarecmd.c

* allow additional 2 ssp_frame cycles to detect SOF
* use only respective functions to get/set iso14a_timeout
* remove waiting time in MifareAcquireEncryptedNonces(). This is covered by GetATQA() now.

fix: hf mf hardnested failed with new WUPA timing

---

client/ui.c

On Android, we handle stdout and logging a little differently.  stdout is also sent to `/dev/null`.  However, there are a number of global variables declared in `ui.c` which are useful for the rest of the application.
This adds a define `EXTERNAL_PRINTANDLOG` which will disable the stock `PrintAndLog` implementation in proxmark3.  If defined, this would require that an implementer bring their own `PrintAndLog` function that implements the same API.
Example implementation for Android given below, which will push logs into the `INFO` log for the application (accessible via Logcat).  A better implementation of this would pull it into the rest of the application's UI.
```c
#include <android/log.h>
#define APPNAME "natives::PrintAndLog"
void PrintAndLog(char *fmt, ...)
{
va_list argptr; …
```

Allow externalisation of PrintAndLog

---

client/loclass/ikeys.c

FIX: 'hf iclass'  - sneaky fread bug.   It should return same number of bytes as read if ok.   Thanks to @bettse who found it.

fix. 'hf iclass' fread bug

---

client/cmdhfmf.c

Sorry for another pull request.
I should have thought twice before submitting the patch...

hf mf nested: use bitwise or instead.

---

client/mifarehost.c

This will solve the long running of the attack, since all candidate keys will be tested.

fix: hf mf mifare -   populate keylist

---

common/usb_cdc.c

Add the BOS USB descriptor. This tells the OS the device supports extended commands, on Android this means the OS allows apps to interact with the device using the Android USB Host API. i.e. apps can communicate with the PM3 without needing root.

Allow non-root access on Android devices

---

client/scripts/lf_bulk_program.lua

Just programmed a few hundred cards using this script and discovered this.  Facility and Site code are not effected by swapping the parity bits but the full hex value is. Some of the systems at my workplace - photocopiers etc.. actually rely on the hex value and not the WG26 decimal numbers this issue became obvious fast.

fix for swapped parity bits

---

client/proxmark3.c
client/ui.c

Extracted from PR #463, this addresses issues when using libedit's compatibility mode for readline, which is used on BSD and OSX.  This patch set has been tested with Linux (using GNU readline), OSX 10.13 (using both libedit and GNU readline).
Using libedit over readline avoids needing to swap in readline over the top of system libraries (`brew link --force readline`), and removes the need to explicitly install readline (as libedit is included on OSX).
1. If compiler optimisations are disabled in OSX, and the user is using libedit, then a link failure occurs, as the second `if (need_hack)` is no longer optimised out.
I've got another branch where I've been attempting to get libedit to have the same functionality as GNU readline.  It mostly works, but arrow keys don't work correctly after …

OSX: Multiple libedit/readline fixes

---

armsrc/mifarecmd.c
armsrc/mifareutil.c

Retry block reads a few times if the CRC is bad instead of bailing immediately

mfu read block: retry block with bad CRC

---

common/lfdemod.c

Commit 1dae9811f22b7f2cea340cee6945cb349046129d extended the amount of fixed bits searched for when decoding 64-bit Indala. These additional bits come from the end of one UID, and therefore need to be skipped past when actually retrieving the UID.
Before:
```
proxmark3> lf indala clone 6effff795
Cloning 64bit tag with UID 6effff795
proxmark3> #db# DONE!
proxmark3> lf indala read
BitLen: 64
Indala UID=1010000000000000
0000000000000000
1101110111111111
1111111011110010
(a0000000ddfffef2)
```
After:
```
proxmark3> lf indala clone 6effff795
Cloning 64bit tag with UID 6effff795
proxmark3> #db# DONE!
proxmark3> lf indala read
BitLen: 64
Indala UID=0000000000000000
0000000000000110
1110111111111111
1111011110010101
(6effff795)
```

Fix offset Indala UID display

---

client/scripts/mfkeys.lua

When input key list size is greater than 85, table.concat() returns empty because the last parameter is the end offset not the increment value.

Fix empty key list bug in mfkeys.lua

---

client/Makefile
client/cmdmain.c
client/cmdmain.h
client/cmdparser.c
client/comms.c
client/comms.h
client/flash.c
client/flash.h
client/flasher.c
client/proxgui.h
client/proxmark3.c
client/ui.c
client/ui.h
uart/uart.h
uart/uart_posix.c
uart/uart_win32.c

* move communication related code from proxmark3.c and cmdmain.c to new file comms.c
* replace byte_t by uint8_t in uart_posix.c and uart_win32.c
* move OpenProxmark() and CloseProxmark() from flasher.c to flash.c
* move print_lock mutex including initializer to ui.c
* minor changes in printing help texts
* no changes in comms functionality yet, just a preparation for PR #463

USB comm: prepare for @micolous change (PR#463)

---

client/cmdlf.c
client/cmdmain.c
client/cmdparser.c
client/comms.c
client/comms.h
client/flash.c
client/flash.h
client/hid-flasher/proxusb.c
client/proxmark3.c
client/ui.c
client/ui.h
common/Makefile.common
common/iso15693tools.c

* change variable 'offline' from global to static
* change variable 'FlushAfterWrite' from global to static
* remove unused global variable 'current_command'
* WaitForResponseTimeoutW(CMD_UNKNOWN, ...) waits for any command
* #include "printf.h" or <stdio.h> in iso15693tools.c to define sprintf()
* and some minor changes/comments

USB comms: part 2 towards @micolous PR#463

---

client/cmdlf.c

notifies user more gracefully of failure - per request #594

more graceful exit to lf search if no signal found

---

client/comms.c
client/proxmark3.c

- CloseProxmark now clears global state (`sp` and `serial_port_name`).
- CloseProxmark now checks for a non-null `sp` before calling uart_close, to avoid unintentional double-free'ing `sp`.
- main now calls CloseProxmark once.
This fixes a crash-on-exit on OSX. This was split from #615.

Fixes a double-free issue in CloseProxmark

---

client/comms.c

This replaces #615, implementing the method of disabling unlink that @pwpiwi suggested in https://github.com/Proxmark/proxmark3/pull/615#issuecomment-398987420.
**Test method:** (using standard Linux build)
Normal build:
```
$ strings client/proxmark3 | grep -c unlink
3
```
Build with `-DNO_UNLINK` appended to `CFLAGS` in `client/Makefile`:
```
$ strings client/proxmark3 | grep -c unlink
0
```

Allow disabling unlink() with -DNO_UNLINK.

---

client/cmdlfhid.c
client/cmdlfhid.h

These are used to pack and unpack the bit length, facility code and card number from "short" HID Prox IDs.  The `unpack` command is based on the code that was in `CmdFSKdemodHID`, and both commands call the new function `unpack_short_hid`.
This also simplifies some repeated code that is used to parse hex digits in `lfhid.c`, and adds basic client-side validation to the `lf hid clone` and `lf hid sim` commands, for when an ID that is too long is entered.
There were some stray tabs in this file which I converted to 2 spaces.
Example data:
```
proxmark3> lf hid pack 35 111 2346
HID Prox TAG ID: 280de01254 (2346) - Format Len: 35 bits - FC: 111 - Card: 2346
proxmark3> lf hid unpack 280de01254
HID Prox TAG ID: 280de01254 (2346) - Format Len: 35 bits - FC: 111 - Card: 2346
proxmark3> lf hid …
```

Adds `lf hid pack` and `lf hid unpack` offline commands.

---

armsrc/Makefile
client/Makefile
common/Makefile_Enabled_Options.common

this is so the client also knows what features are available after compile.  
makes it easier to turn on and off features if and when needed.
this will come more in handy as alternative hardware continues to pop up (RV4).  we can create features that are only available for specific hardware and include or exclude them in the new Makefile_Enabled_Options.common file.
one example is smartcard addon that the RV4 has.

allow common makefile options-defines

---

CHANGELOG.md
armsrc/legicrf.c
armsrc/legicrf.h
fpga/hi_read_tx.v
include/legic.h

As already discussed in #652 I've rewritten most of the Legic Prime reader code to use xcorrelation and precise timing in preparation of a new simulator (not included yet).
With the new code I'm getting reading distances of up to 15cm. Photographer @iceman1001:
Beyond that distance, the modulation is simply not distinguishable from background noise.
This pull request is based on a similar implementation I've made for Proxmark3 Rdv4, a couple of days ago iceman1001/proxmark3#227. The code still builds upon the initial concept of Henryk Plötz and contains refinements from Iceman.
Even tough this PR conflicts with #652 I've decided to start the review process now. The code is completely stable and well tested. Moreover adjusting for the upcoming bumped sample rate should be a breeze.

Legic: rewrite reader to use xcorrelation and precise timing

---

armsrc/legicrf.c

Due to an oversight the bytes to be written were fetched from the wrong location. This is fixed now.
I falsely assumed only data to be written would be loaded into BigBuf. However BigBuf always holds a full copy of the tags data.
Sorry for not noticing this earyler.

Legic: fix write

---

client/cmdlfhid.c
client/cmdlfhid.h

Included in this update:
* Parity calculation has been completed for all HID formats previously programmed.
* Support for packing/unpacking long-tag HID Corporate 1000 48-bit has been added.
* Removal of the 'l' (long) flag on clone (now autodetected)
Please note that simulation of long HID tags is still not directly supported, as that feature requires a change to the embedded firmware in addition to client updates.

client: lf hid - parity completed, native long-tag support in pack/unpack/clone

---

armsrc/legicrfsim.c

As discussed with Iceman, this helps quitting Legic simulation function without pressing the physical button.
One can cleanly quit the Legic simulation mode by issuing another command involving USB communication such as "hf legic reader".

Allow clean Legic simulation exit without button press

---

armsrc/fpgaloader.h

FpgaSetupSscDma uses uint16_t and not int with #669

fpgaloader: fix function accordingly to #669

---

armsrc/Makefile
armsrc/appmain.c
armsrc/apps.h
armsrc/i2c.c
armsrc/i2c.h
armsrc/iso14443a.c
armsrc/mifaresim.c
include/proxmark3.h

* detect and use RDV40 higher voltage ADC channel for hw tune, hf tune, hw detectreader
* fix mode switching in hw detectreader
* detect Smartcard Slot in hw version
* i2c changes from https://github.com/RfidResearchGroup/proxmark3
* some formatting in proxmark3.h

RDV40 compatibility fixes

---

client/jansson/error.c
client/jansson/load.c

Fix GCC 8 warnings stringop-truncation, stringop-overflow and format-truncation.

Jansson gcc8 fix

---

client/comms.c

In Android O and later, if an invalid (or defunct) `pthread_t` is passed to `pthread_join`, it calls `fatal()`:
https://github.com/aosp-mirror/platform_bionic/blob/ed16b344e75f422fb36fbfd91fb30de339475880/libc/bionic/pthread_internal.cpp#L116-L128
This patch addresses it by:
1. Always `memset(0)` on `USB_communications_thread` at the end of `CloseProxmark`.
2. On Bionic, only call `pthread_join` on `USB_communications_thread` if it is not equal to 0.
This addresses https://github.com/AndProx/AndProx/issues/23, an issue similar to #617. 
Tested:
- Android SDK 21
- Android SDK 27
- Linux x86_64

FIX: crash on Bionic libc if CloseProxmark is called twice.

---

client/proxguiqt.cpp

The ControlWidget is placed below the PlotWidget and resized to match the PlotWidget width.

Fix: ControlWidget placement

---

CHANGELOG.md
client/Makefile
client/comms.c
client/util_darwin.h
client/util_darwin.m

Apple introduced app-nap with OS X 10.10. This feature saves power by throttling apps running in background. However, it also less accurate timers in systemcalls. In our case a 30ms select timeout would take up to 10s.
This patch uses an API also added with 10.10 to disable app-nap as long as the serial port is polled and fixed #283, fixed #627.

osx: disable app-nap during serial comm

---

client/Makefile
client/cliparser/cliparser.h
client/cmdhfmfp.c
client/emv/test/cryptotest.c
client/mifare4.c
client/mifare4.h
common/polarssl/aes_cmac128.c
common/polarssl/aes_cmac128.h
common/polarssl/libpcrypto.c
common/polarssl/libpcrypto.h

`hf mfp` can `rdbl` and `rdsc` in plain mode
plus:
- aescmac128
- tests for aescmac
TODO:
- move from **polarssl** to **mbedtls**
_I dont know the MAC calc procedure. so i leave `wrbl` command to time when it will be possible._

Mfp read plain

---

client/util.c

Fix missing include in #716:
```
util.c: In function ‘FillBuffer’:
util.c:116:2: error: unknown type name ‘va_list’
va_list valist;
^~~~~~~
util.c:116:2: note: ‘va_list’ is defined in header ‘<stdarg.h>’; did you forget to ‘#include <stdarg.h>’?
util.c:30:1:
+#include <stdarg.h>
util.c:116:2:
va_list valist;
^~~~~~~
util.c:117:2: warning: implicit declaration of function ‘va_start’ [-Wimplicit-function-declaration]
va_start(valist, dataLength);
^~~~~~~~
util.c:122:11: warning: implicit declaration of function ‘va_arg’; did you mean ‘alarm’? [-Wimplicit-function-declaration]
vdata = va_arg(valist, uint8_t *);
^~~~~~
alarm
util.c:122:26: error: expected expression before ‘uint8_t’
vdata = va_arg(valist, uint8_t *);
^~~~~~~
util.c:126:28: error: expected expression before ‘size_t’
vlength = …
```

Fix util.c missing include

---

client/cmdhfmf.c

This is based on PR #700.
Note: this is a quick fix for the time being and still has its drawbacks (e.g. tdss doesn't work without propoer error message, position of flags is not arbitrary, flags must be concatenated).  Should be replaced by argtable parsing sooner or later.

fix "hf mf chk" <t|d|s|ss> flags

---

client/crypto/asn1dump.c
client/ui.c

Fix these warnings:
```
ui.c: In function ‘PrintAndLogEx’:
ui.c:102:41: warning: ‘%s’ directive output may be truncated writing up to 2047 bytes into a region of size between 2029 and 2048 [-Wformat-truncation=]
snprintf(buffer2, sizeof(buffer2), "%s%s", prefix, buffer);
^~           ~~~~~~
ui.c:102:3: note: ‘snprintf’ output between 1 and 2067 bytes into a destination of size 2048
snprintf(buffer2, sizeof(buffer2), "%s%s", prefix, buffer);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mv -f obj/ui.Td obj/ui.d
gcc -MT obj/comms.o -MMD -MP -MF obj/comms.Td  -std=c99 -D_ISOC99_SOURCE -I. -I../include -I../common -I../common/polarssl -I../zlib -I../uart -I/opt/local/include -I../liblua -I./jansson -I../common/mbedtls -Wall -g -O3  -DWITH_ISO14443a_StandAlone -DWITH_LF …
```

Fix format-truncation warning, missing string.h inclusion and strnlen warning

---

client/cmdhffido.c

Fix `ERROR: public key length must be 65 bytes only` when submitting a valid public key.

Fido - fix public key lenght to 65 bytes

---

uart/uart_posix.c

On ChromeOS Linux apps can't access serial port but they can connect to TCP,
so I wrote a simple app to forward TCP to serial. I suppose this can
have other uses as well.

Support TCP ports for proxmark

---

armsrc/appmain.c
armsrc/pcf7931.c
armsrc/pcf7931.h
client/cmdlfpcf7931.c
client/cmdlfpcf7931.h
include/usb_cmd.h

I've tried to clean PCF7931 read code to make it easier for others to understand what's going on.
I've tried to clean console output too: now there's an indicator showing how many blocks have been read (and ordered) and the blocks with unknown positions will be printed only at the end of the command execution without spamming the console.
There's also a new password bruteforce command for the PCF7931 transponders, I think it's still not feasible to find the password this way but it may be a starting point for future improvements

PCF7931: improved read code and implemented a simple password bruteforce

---

include/usb_cmd.h

Fix issue:
```
appmain.c: In function 'UsbPacketReceived':
appmain.c:1074:3: error: duplicate case value
case CMD_VIKING_CLONE_TAG:
^~~~
appmain.c:1062:3: note: previously used here
case CMD_PCF7931_BRUTEFORCE:
^~~~
make[1]: *** [../common/Makefile.common:81: obj/appmain.o] Error 1
```

Fix CMD_PCF7931_BRUTEFORCE duplicate case value in usb_cmd.h

---

armsrc/legicrfsim.c

Bug reports from @raphCode and @uhei over at the RfidResearchGroup/proxmark3#83 have shown that the tag to rwd timeout is too short.
I still don't know that the best choice is. If the timeout is too short the tag returns too early to idle. If the timeout is too long the tag might never return to idle since it considers reconnects to be still the old connection. That sed both reported success with the new timeout.

Legic TagSim: increased reader timeout

---

client/cmdhffido.c
client/cmdsmartcard.c
client/cmdsmartcard.h
client/emv/cmdemv.c
client/emv/emvcore.c
client/emv/emvcore.h
client/fido/fidocore.c
client/fido/fidocore.h
client/pcsc.c
client/pcsc.h
client/proxmark3.c
common/protocols.h

* add PCSC reader support to 'sc raw' and all 'emv' commands
* move all APDU -> TPDU mapping to ExchangeAPDUSC()
* print "PSE" instead of "PPSE" when using contact interface
* fix some #defines in protocols.h
* DropField only when using contactless
* some refactoring

Adding support for standard USB Smartcard Readers (cont.)

---

client/cmdhffido.c
client/emv/cmdemv.c
client/emv/emvcore.c
client/emv/emvcore.h
client/fido/cbortools.c
client/fido/fidocore.c
client/pcsc.c

* print selected Smartcard Reader in PrintChannel()
* implement 'sc sel \<readername\>'. Readername can include wildcards * and ?
* fixing EMV APDU exchange (again). fix #775 had broken emv commands using contact interface
* use EMVExchangeEx() instead of EMVExchange() in fidocore.c

emv/sc fixes and modifications:

---

uart/uart_posix.c

Since PR #720 USB uart communications are slow:
For example, dumping a Mifare 1K card take up to 20 seconds now !
```
Saving magic mifare 1K 
Start |        End | Src | Data (! denotes parity error)                                   | CRC | Annotation         |          
------------|------------|-----|-----------------------------------------------------------------|-----|--------------------|          
0 |        992 | Rdr | 40                                                              |     | MAGIC WUPC1          
2244 |       2820 | Tag | 0a!                                                             |     |           
7040 |      11808 | Rdr | 30  00  02  a8                                                  |  ok | READBLOCK(0)          
12996 |      33860 | Tag | **  **  **  ** …
```

Fix for USB uart slowness since PR #720

---

armsrc/iso14443a.c
armsrc/iso15693.c

* LED_A (yellow): PM3 is active (snooping)
* LED_B (green): reader is sending a command
* LED_C (red): tag is sending a reply

fix LED signalling in hf 15 snoop and hf 14a snoop

---

armsrc/fpgaloader.c

* ouch! Be aware that same major modes are used in LF and HF!
This should fix issue #806.

fix FpgaSetupSsc() (issue #806)

---

client/cmddata.c
client/cmdlffdx.c

In CmdBiphaseDecodeRaw it was not possible to set an maxErr-value, because cmd was restricted to strlen 3. Now its 5, so its possible to enter an maxErr-value between 0-9. Maybe it should be 7 to allow values from 0-999?
_(changed the comment a bit, too)_
In ASKbiphaseDemod the help text says 
> [set maximum allowed errors], default = 100
but in fact default was 0 errors. Changed to 100, so it works like expected.
The function CmdFdxDemod uses ASKbiphaseDemod and sets maximum allowed errors to 0. If you have any demod-error here, FDX-demod fails. Set to 100, because its standard as mentioned above. 
Now i'm able to demod FDX. :)

Fixed bugs for FDX-B demod

---

CHANGELOG.md
armsrc/legicrf.c
client/cmdhf.c
client/cmdhflegic.c

Before these commits, `hf search` didn't try reading Legic tags. To include these, I also had to improve the handling of the `hf legic` command, since from the client perspective, it was pretty much fire-and-forget, as the only feedback came in the form of human-readable `DbpString` calls. I replaced these with proper `CMD_ACK` responses, it worked on my setup:
```
proxmark3> hf search
#db# Reading card ...
Waiting for a response from the proxmark...
You can cancel this operation by pressing the pm3 button
Card (MIM 1024) read, use 'hf legic decode' or
'data hexsamples 1024' to view results
Valid Legic Tag Found - Quiting Search
```

Added support for Legic tags to `hf search` command

---

CHANGELOG.md
armsrc/BigBuf.c
armsrc/BigBuf.h
armsrc/appmain.c
armsrc/apps.h
armsrc/fpgaloader.c
armsrc/iso14443a.c
armsrc/iso14443a.h
armsrc/mifaresim.c
armsrc/mifaresim.h
armsrc/mifareutil.c
armsrc/mifareutil.h
client/cmdhflist.c
client/cmdhfmf.c
include/usb_cmd.h

* fix parity encryption (thanks to Eloff, http://www.proxmark.org/forum/viewtopic.php?id=6347)
* add support to simulate Mifare Mini, Mifare 2K and Mifare 4K
* change to standard LED handling (A: PM is working, B: reader is sending, C: tag is responding, D: HF field is on)
* whitespace

fix hf mf sim

---

client/cmdlf.c

Fix typo: `q <divisor>   Manually set divisor. 88-> 134KHz, 95-> 125 Hz`

Fix typo lf config usage

---

CHANGELOG.md
armsrc/lfops.c
client/cmdlft55xx.c
client/cmdlft55xx.h

Added options to select t5577 downlink modes for commands
lf t55xx detect, read, write and bruteforce.
Where supported it will use the 'r' option, such that: 
r 0  - fixed bit length (default), 
r 1  - long leading reference
r 2 -  leading zero
r 3 - 1 of 4 coding reference

lf t55xx downlink modes support added

---

CHANGELOG.md
armsrc/appmain.c
armsrc/iso15693.c
armsrc/iso15693.h
client/cmdhf15.c
client/cmdhf15.h
include/usb_cmd.h

Based on the commands in Iceman's lua script, here is the command to set UID on ISO15693 Magic tags.
```
proxmark3> hf 15 reader
proxmark3> #db# 12 octets read from IDENTIFY request:
#db# NoErr CrcOK
#db# 00 00 11 11 11 11 11 11
#db# 11 e0 28 01
#db# UID = E011111111111111
proxmark3> hf 15 csetuid E022222222222222
new UID | e0 22 22 22 22 22 22 22
Using backdoor Magic tag function
received 0 octets
received 0 octets
received 3 octets
00 78 F0
received 3 octets
00 78 F0
old UID : e0 11 11 11 11 11 11 11
new UID : e0 22 22 22 22 22 22 22
proxmark3> hf 15 reader
proxmark3> #db# 12 octets read from IDENTIFY request:
#db# NoErr CrcOK
#db# 00 00 22 22 22 22 22 22
#db# 22 e0 db 86
#db# UID = E022222222222222
proxmark3>
```

Add 'hf 15 csetuid' command to set UID on ISO15693 Magic tags

---

CHANGELOG.md
client/cmdhfmf.c

Patched so that a single block key check will write to the emulator if found.
Updated the display output for a single block check to use the same format as the full card check.
Added a count and display the number of keys found and transferred.
Ensured that a write to the dump file wont happen if a single block check was used.

Issue #843 - hf mf chk - t Doesnt save to emulator memory 

---

CHANGELOG.md
client/cmdhffido.c
client/cmdhfmfu.c
client/crypto/libpcrypto.c
client/crypto/libpcrypto.h
client/fido/fidocore.c
common/mbedtls/check_config.h
common/mbedtls/config.h
common/mbedtls/ecdsa.c
common/mbedtls/ecdsa.h
common/mbedtls/ecp.c
common/mbedtls/ecp.h
common/mbedtls/ecp_curves.c

* add support for elliptic curve 'secp128r1' to mbedtls library
* change ecdsa_signature_verify() to allow different curves, signature lengths, and skipping hash
* add originality check in 'hf mfu info'
* add another public key for Mifare Ultralight EV1

Implement Originality Signature Check

---

CHANGELOG.md
armsrc/mifaresim.c

(from PR 279 https://github.com/RfidResearchGroup/proxmark3)

fix 'hf mf sim': wrong access rights to write key B in trailer

---

armsrc/mifarecmd.c
client/cmdhfmf.c

* don't repeatedly clear trace while running (PR 243 by @mceloff on https://github.com/RfidResearchGroup/proxmark3)
* standard LED handling
* better check for key file syntax
* get rid of "res" column when printing the result. Show unknown keys more prominent as "     ?     "

update 'hf mf chk'

---

armsrc/appmain.c
armsrc/iclass.c
armsrc/iclass.h
client/hid-flasher/usb_cmd.h
include/usb_cmd.h

* remove unused CMD_ICLASS_READCHECK
* fix wrong command coding in CodeIClassCommand()
* switch field off at end of commands to avoid RDV4 overheating

fix iclass reader functions

---

armsrc/appmain.c
armsrc/iclass.c
client/cmdhficlass.c
client/hid-flasher/usb_cmd.h
common/iso15693tools.c
common/iso15693tools.h
include/usb_cmd.h

* implement option -n for authentication with replayed NR/MAC pairs in 'dump' and 'readbl'
* delete 'hf iclass replay' which no longer adds value

fix 'hf iclass replay'

---

client/hidcardformats.c

The 'PrintAndLog' calls were using signed types and sometimes too few bits in width for formatting/outputting the data as was revealed in the forums. This commit will correct the printf-formatted output typing on display of the fields.

Bugfix: Output typing on print of HID card formats

---

client/cmdhfmf.c

FIX: command "hf mf ekeyprn  d" doesn't use the correct offset to locate the A key in data[] array and record the 2 last bytes followed by 4 0x00 instead of the 6 good bytes (All the A keys are corrupted in file dumpkeys.bin). B keys are not affected.
Fix issue #903

"hf mf ekeyprn d" doesn't works properly

---

armsrc/iclass.c
client/cmdhficlass.c

* check for correct responses after block updates
* reduce number of tries from 10 to 3
* Allow to override warning on attempt to clone blocks < 5
* add same warning and override option to 'hf iclass writebl'
* some reformatting and minor refactoring

fix 'hf iclass writebl' and 'hf iclass clone'

---

armsrc/iso14443a.c
armsrc/iso14443a.h
armsrc/mifarecmd.c
armsrc/mifarecmd.h
armsrc/mifareutil.c
armsrc/mifareutil.h
client/cmdhfmf.c
client/mifare/mifarehost.c
client/mifare/mifarehost.h

* add separate timeout for tag response to nr_ar
* measure response time and use it for response timeout
* don't drop field between keyblocks
* some reformatting
* some whitespace fixes

speedup 'hf mf chk'

---

client/util.c

Mindless fix for #912, returning `0` in case of error instead of `-1`.

Fix #912: ukbhit() false positive

---

client/cmdhfmf.c

correctly display "SUCCEEDED" or "FAILED"

fix 'hf mf perso' result feedback

---

client/comms.c

compatibility fix: get_clocktime() is not a available with older glibc

---

client/ui.c

Failed to compile without adding <string.h> lib to ui.c in /client on MacOS Big Sur Developer Beta. Received this error when doing `make clean; make` to compile the software in Step 19 of the Getting Started [instructions](https://github.com/Proxmark/proxmark3/wiki/MacOS): 
> ui.c:52:4: error: implicitly declaring library function 'strncpy' with type
'char *(char *, const char *, unsigned long)'
[-Werror,-Wimplicit-function-declaration]
strncpy(prefix,_RED_(FAILED: ), sizeof(prefix)-1);
^
ui.c:52:4: note: include the header <string.h> or explicitly provide a
declaration for 'strncpy'
ui.c:79:6: error: implicitly declaring library function 'strchr' with type 'char
*(const char *, int)' [-Werror,-Wimplicit-function-declaration]
if (strchr(buffer, '\n')) {
^
ui.c:79:6: note: include the …

Compile Error: Add string.h to ui.c

---

armsrc/hitagS.c

Avoid link error due to duplicate definition of blocknr in hitag2.c and hitagS.c

---

armsrc/string.c
armsrc/string.h

- remove unnecessary memxor(), strreverse(), and itoa() functions
- Use correct types in function declarations and definitions
- add memmove() function. Gcc may generate calls to memcmp(), memcpy(), memset() and memmove()

Cleanup armsrc/string.c and string.h
